clc;clear

a = [1 2 3 4];

a(1:end/2)      %DEVUELVE LA MITAD DEL VECTOR 
a(end + 1) = 5  %AGREGA UN NUEVO ELEMENTO AL VECTOR
a(end) = []     %QUITA EL ELEMENTO AGREGADO
a(1:2:end)      %EXTRAE DATOS DEL VECTOR DE 2 EN 2, EMPEZANDO POR LA POSICION 1
a(2:2:end)      %EXTRAE DATOS DEL VECTOR DE 2 EN 2, EMPEZANDO POR LA POSICION 2
a(end:-1:1)     %INVIERTE EL VECTOR